version: '3'

services:
  vscode:
#    build: ./vscode
    image: "vscode-image"
    container_name: vscode1
    volumes:
      - /opt/docker-image/vscode-package/vscode/package/:/var/cache/apt/archives/
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - SETFCAP
      - CHOWN
      - FOWNER
      - FSETID
      - DAC_OVERRIDE
