version: '3'

services:
  docker-image:
    image: "docker-image-image"
    container_name: docker-image1
    volumes:
      - /opt/docker-image/docker-image-package/docker-image/image/:/image
    #environment:
    #  - imagename
    #  - tag
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - SETFCAP
      - CHOWN
      - FOWNER
      - FSETID
      - DAC_OVERRIDE
